### ISSUE TITLE
Expose all flags in msghdr send/recv_vectored function

### ISSUE THREAD

**Issue by Thomasdezeeuw** [alexcrichton/socket2-rs#113]
Pr #107 added vectored I/O and currently returns a boolean indicating if the buffer was truncated. But the `flags` field on `msghdr` give us more information. This issue is about nicely (and cross-platform) exposing that information.

Some ideas:
* Add our own `msghdr` like structure that can be checked after a call to send/recv. Downside: input, output arguments are very "rustic".
* Instead of returning a boolean indicating truncation, change it to the entire `flags` field wrapped in a new type. Such a new type could be `SendFlags` with function such as `is_truncated(&self) -> bool`.

/cc @de-vri-es

**Comment by de-vri-es** [comment]
I like the flags type idea. It also makes the return type more intuitive: `(usize, RecvFlags, SockAddr)` instead of `(usize, bool SockAdd)`.

There are no flags to return when sending messages, btw. But I think `RecvFlags` is still a good name. It would allow to create a `SendFlags` type later for the flags argument.

It probably makes sense to do this before releasing vectored I/O, to prevent backwards incompatibilities. Initially it could even just expose `is_truncated()` until support for more flags is added.

Implementing this on Windows will be a bit harder. The flags are only used to report 'MSG_PARTIAL`, which is not the same as `MSG_TRUNC`. Truncated messages are reported as error, which can be turned into a flag. But the `MSG_EOR` and `MSG_OOB` flags aren't reported at all.

For `MSG_EOR` that doesn't matter: Windows has no connection oriented datagram sockets, so the flag wouldn't be reported anyway. I don't see a way to detect `MSG_OOB` on Windows. It appears that it can only be used as input flag.

**Comment by de-vri-es** [comment]
PR opened at #114 :)

**Comment by de-vri-es** [comment]
#114 was merged :)

Do you think that there is more that should be done?

**Comment by Thomasdezeeuw** [comment]
Nope.
